### ISSUE TITLE
I made some changes..

### ISSUE THREAD

**Issue by techwithanirudh** [andrewwoan/abigail-bloom-portolio-bokoko33#4]
I tried to create a pull request, but unfortunately encountered some issues. As a result, I have linked my repository here: https://github.com/techwithanirudh/portfolio-v2/. Within the repository, I have added a new file called constants.js, which allows users to input their own information for the portfolio. Additionally, I have included a scroll-down button to enhance the user experience.

However, I have noticed that there is an issue with scrolling down using the page down button in Microsoft Edge on Windows 11 22H2. Instead, you need to perform a pinch gesture on the touchpad to make the "Hello..." message disappear and the 3D room to zoom in. Do you have any ideas why this might be happening?

**Comment by andrewwoan** [comment]
The link to your github gives 404 error.

For that issue, I'm not sure, it doesn't seem to cause any problems on my end, What device are you using? Laptops generally require two fingers to swipe up in order for it to activate, a pinch gesture is a little odd.

**Comment by techwithanirudh** [comment]
sry, It was private

**Comment by techwithanirudh** [comment]
No, when I try to scroll down using the page down buttons it won't work. How can I fix this?

**Comment by andrewwoan** [comment]
If you mean the page down button on your keyboard, it doesn't work because there is no page to scroll down. The page is only 100VH and the rest of the content is overflowed hidden sliding across the viewport which means it doesn't contribute to the page's length.

**Comment by techwithanirudh** [comment]
Can you please tell me which function is responsible for animating the room to fullscreen? I believe I can add a JavaScript addEventListener for keypress and use an if condition to achieve the desired result. Do you think this approach would be effective?

**Comment by andrewwoan** [comment]
I'll need some time to check it, working some other current projects. Just make sure you change up the design if you haven't already. The original creator requests this. 

Yes, you can add another section by simply copying one of the left sections in the html and pasting it where you want it, the rest of the code should still work properly.

**Comment by techwithanirudh** [comment]
I did change the loader and trying different color schemes, anything else to do?

**Comment by andrewwoan** [comment]
Yeah the section design could be different or the 3D model. 

You can create the circle in the same file we created the other circles and select it with the gsap tween. Same thing with the room position, copy one of the GSAP tweens we did for one of the other sections in the video and move it to your desired location.
